version: '2'
services:
  dockerapp:
    image: dockerapp
    environment:
      - constraint:node==master
    depends_on:
      - redis
    networks:
      - my_net

  redis:
    image: redis:3.2.0
    networks:
      - my_net

networks:
  my_net:
    driver: bridge
